
Vagrant.configure("2") do |config|
  config.vm.define "vm2" do |vm2|
   vm2.vm.box = "ubuntu/focal64"
  end
  config.vm.network "private_network", type: "static", ip: "192.168.56.20"
  config.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "2048"
  end
  config.vm.provision "shell", path: "provision.sh"
end
