
Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
   vm1.vm.box = "ubuntu/focal64"
  end
  config.vm.network "private_network", type: "static", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "2048"
  end
  config.vm.provision "shell", path: "provision.sh"
end
